### ISSUE TITLE
要安装gurobi或者 CPLEX Studio才能使用jabba？

### ISSUE THREAD

**Issue by wwhwwxlz** [mskilab-org/JaBbA#101]

**Comment by wwhwwxlz** [comment]
[root@DC5-09-006 cplex_studio2211-osx-arm64.app]# find . -name cplex
[root@DC5-09-006 cplex_studio2211-osx-arm64.app]# ls
我在IBM下载的包里没有找到cplex二进制文件

**Comment by shihabdider** [comment]
You can use either CPLEX or gurobi. 

See: https://github.com/mskilab-org/JaBbA?tab=readme-ov-file#installation-from-github
