### ISSUE TITLE
Make the C functions compilation compatible with MacOS

### ISSUE THREAD

**Issue by xtYao** [mskilab-org/JaBbA#12]
Modify the `configure.ac` script. I think it is not recognizing the current `$CPLEX_DIR` as the desired variable but `$CPLEX_DIR/cplex`. Hence every time it is trying to re-infer the path from `$CPLEX_BIN` file location.

**Comment by roseisgold** [comment]
I ran into this issue as well, but worked around it by modifying the srcs/src.rcplex/Makevars file to point to _osx instead of linux and then had to reinstall the package with R CMD INSTALL
