### ISSUE TITLE
JaBbA crashes when DNAcopy::segment returns reverse strand segments

### ISSUE THREAD

**Issue by pwaltman** [mskilab-org/JaBbA#19]
I suspect that this is a problem on the side of DNAcopy, and it's an issue I ran into when I was working on getting the fragCounter module going; but for whatever reason, DNAcopy::segment (called on line 690 in JaBbA.R) is returning segments where the $out$loc.end value is les than $out$loc.start. This, in turn, causes an error when seq2gr is called on line 696.

I don't understand why it is doing this as none of the ranges in my coverage object have negative lengths. It's just something that DNAcopy::CNA or DNAcopy::segment is doing.  The quick workaround is something like this:
```
            if ( any ( seg$out$loc.end < seg$out$loc.start ) ) {
                whch <- which( seg$out$loc.end < seg$out$loc.start )
                whchBak <- seg$out$loc.start[ whch ]
                seg$out$loc.start[whch] <- seg$out$loc.end[ whch ]
                seg$out$loc.end[ whch ] <- whchBak
            }
```

**Comment by xtYao** [comment]
Could you provide partially your coverage input data, particularly the part where this negative width segment is produced? Maybe send me a Dropbox link. We've never seen this error before.

**Comment by pwaltman** [comment]
Sure. I'll post it to Dropbox, and will PM you a link

**Comment by pwaltman** [comment]
Done. I've sent you the link to a tar.bz2 file which contains the cov.rds, as well as the scripts I used to generate the files for fragCounter.
