### ISSUE TITLE
Sequenza has been removed from CRAN

### ISSUE THREAD

**Issue by p-smirnov** [mskilab-org/JaBbA#91]
**Describe the bug**
It seems like Sequenza has been removed from CRAN earlier this year, and its a dependency of this package. Therefore, normal package installation fails. 

**To Reproduce**
Try to install the package in a new environment without any dependencies available.

Suggestions to resolve: Either change to depend on the bitbucket hosted version of Sequenza, provide instructions on how to install from CRAN archive (or work around the dependency).

**Comment by tpersse** [comment]
Our group had similar issues. Resolved by doing the following in R, after changing R version to 4.0.2 (more recent versions might work, but this one was mentioned in a yaml file in the repository):
> install.packages("BiocManager")
> install.packages('testthat')
> BiocManager::install(c("copynumber", "iotools", "squash", "seqminer")) # dependencies for sequenza
 
> install.packages("~/sequenza_3.0.0.tar.gz", repos = NULL, type="source")

We had to install an archived version of sequenza from [this link](https://cran.r-project.org/src/contrib/Archive/sequenza/)

Additionally, we ended up having to install DelayedArray and VariantAnnotation packages through BiocManager, then installing 'mskilab-org/gTrack' and 'mskilab-org/gGnome' before installing JaBbA. Hope this can help.
